## NumPy

-> Numpy is a python package stands for numeric python
-> Numpy is ised perform mathematical calcualtion in python
-> it is used by importing numpy library
-> it consists of multidimensional arrays and metrices along with a collection of operations that we can perform on numpy arrays
-> it provides many functions which leads to effeicient and fast operations

In [1]:
import numpy as np

numpy arrays 1d array

In [2]:
one_d_array = np.array([1,2,3])       # creating numpy arrays

In [3]:
print(one_d_array)

[1 2 3]


In [4]:
type(one_d_array)       # ndarray is n dimensional array used to manipulate arrays such as 1D, 2D, 3D, etc

numpy.ndarray

### Creating 1D array using list

In [5]:
list = [2,4,6,8]

In [6]:
arr1 = np.array(list)

In [7]:
print(arr1)

[2 4 6 8]


In [8]:
# creating 2D array

In [9]:
two_d_array = np.array([[1,3,5,7,9],[2,4,6,8,10]])  #creating 2d array using two 1d array in []'s

In [10]:
print(two_d_array)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [11]:
print(two_d_array.shape)    # this shows the shape of two_d_array with 2 rows and 5 columns

(2, 5)


In [12]:
print(two_d_array.size)       #this shows number of elements in the array

10


In [13]:
print(two_d_array.ndim)      #this shows the dimension of array

2


In [14]:
print(two_d_array.dtype)   #this shows data type of array that types of elements stored in array

int32


In [15]:
print(two_d_array.itemsize)   # this shows size of each element of array in bytes as memory usage of each element

4


In [16]:
# creating 3D array 

In [17]:
arr3 = np.array(
    [
        [
            [1,2,3],
            [4,5,6],
            [11,22,33]
        ],
        [
            [7,8,9],
            [10,11,12],
            [44,55,66]
        ],
        [
            [13,14,15],
            [16,17,18],
            [77,88,99]
        ]
    ]
)

#### 3D array is created using two or more 2D arrays

In [18]:
print(arr3)
print(arr3.shape)
print(arr3.size)
print(arr3.ndim)
print(arr3.dtype)
print(arr3.itemsize)

[[[ 1  2  3]
  [ 4  5  6]
  [11 22 33]]

 [[ 7  8  9]
  [10 11 12]
  [44 55 66]]

 [[13 14 15]
  [16 17 18]
  [77 88 99]]]
(3, 3, 3)
27
3
int32
4


### Memory comparision of Python list and Numpy arrays

In [19]:
import sys

In [20]:
list1 = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]

In [21]:
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [22]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

In [23]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [24]:
list_memory = sys.getsizeof(list1) * len(list1)      # provides the total number of bytes consumed by elements of list

In [25]:
print(list_memory)

2760


In [26]:
array_memory = arr.nbytes     # provides the total number of bytes consumed by elements of array

In [27]:
print(array_memory)

60


###  list vs array

In [28]:
ls = [11,22,33]

In [29]:
ar = np.array([11,22,33])

In [30]:
print(ls+4)    # list donot support this functional operations

TypeError: can only concatenate list (not "int") to list

In [31]:
print(ar+4)   # arrays support this functional operations

[15 26 37]


### Creating arrays in different ways

In [32]:
zeros = np.zeros(4)    # create a array filled with zeroes 
                       #  by default it's data type of float

In [33]:
print(zeros)
print(zeros.dtype)

[0. 0. 0. 0.]
float64


In [34]:
z1 = np.zeros((3,3))  # creates 2D array filled with zeroes

In [35]:
print(z1)
print(z1.ndim)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2


In [36]:
one = np.ones(5, dtype="int")      #create a array filled with ones
                                  # by default it's data type of float
                                    # but we can specify dtype int

In [37]:
print(one)
print(one.dtype)
print(one.ndim)

[1 1 1 1 1]
int32
1


In [38]:
o2 = np.ones((3,3,3),dtype="int")       # creates 3D array of ones

In [39]:
print(o2)
print(o2.ndim)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
3


In [40]:
arr_all = np.full(3,30)    # creates the 1D array which consists of 3 elements and have all 3 values as 30

    numpy.full(shape, fill_value, dtype=None, order='C')


In [41]:
print(arr_all)

[30 30 30]


In [42]:
arr4 = np.full((4,6),99)           # creates the 2d array consists of 99 

In [43]:
arr4

array([[99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99]])

In [44]:
arr5 = np.full((2,2,2),4)

In [45]:
print(arr5)
print(arr5.ndim)

[[[4 4]
  [4 4]]

 [[4 4]
  [4 4]]]
3


In [46]:
arr6 = np.identity(3)                 # creates the identity array or metrix

In [47]:
print(arr6)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# creating array using arange

Arange
        -> using arange we can create array of specific elements of our desired range in asending order
        -> numpy.arange([start, ]stop, [step, ], dtype=None)
        -> we can control the elements of array while creating wiht start stop step and dtype


In [48]:
arr7 = np.arange(10)            # creates the 1D array consists of  0 to 9  elements

In [49]:
arr7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr8 = np.arange(0,11,2)
arr8

array([ 0,  2,  4,  6,  8, 10])

linespace,

numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)


In [51]:
arr9 = np.linspace(0,1,5)  #create a evenly sapced number with specific number of elements 

In [52]:
print(arr9)

[0.   0.25 0.5  0.75 1.  ]


In [53]:
arr10 = np.linspace(0,10,30)  # it creates the list of number from 0 to 10 in 30 equal parts

In [54]:
arr10

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [55]:
arr11 = np.linspace(0,10,retstep=True)     # return step (retstep) shows the difference between two adjecent numbers from the array

In [56]:
print(arr11)                 

(array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ]), 0.20408163265306123)


In [57]:
arr12 = np.random.random(5)               # generates the 1D array of 5 random number between 0 to 1

In [58]:
arr12

array([0.55897878, 0.00133869, 0.7079722 , 0.30418232, 0.07586179])

In [59]:
arr13 = np.random.random((2,3))        # generates the two dimensional array with  2 rows and 3 columns 

In [60]:
arr13

array([[0.11612124, 0.27752386, 0.02185909],
       [0.25062496, 0.59213513, 0.08646452]])

In [61]:
arr14 = np.random.randint(1,100,(2,2))   # generates the 2d array with 2 rows and 2 columns of random integers between 1 to 100

In [62]:
arr14                                # each and every time i execute this cell it generated differents nuymbers

array([[71, 83],
       [54, 78]])

In [63]:
arr15 = np.random.rand(3,4)
arr15

array([[0.95369844, 0.29036229, 0.56905474, 0.05695841],
       [0.54637062, 0.57163232, 0.33013097, 0.98205172],
       [0.29315518, 0.04632692, 0.85397252, 0.76317046]])

## Note: 
        np.random.rand() does not require tuples to specify shape 
        np.random.random() requires tuple to specify shape 

### Indexing and Slicing Numpy Arrays

    -> Numpy arrays each elements are associated with index that starts from 0 
    -> accessing numpy arrays is very much similar to accessing python list
    -> Slicing is to extract the part form array 
    -> array[start:stop:step]

In [64]:
arr7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
arr7[2:6]

array([2, 3, 4, 5])

In [66]:
arr16 = np.array([[2,4,6,8],[1,3,5,7]])
arr16

array([[2, 4, 6, 8],
       [1, 3, 5, 7]])

In [67]:
print(arr16[0][0])
print(arr16[1][0])
print(arr16[0][1])
print(arr16[1][1])
print(arr16[0][2])
print(arr16[1][2])
print(arr16[0][3])
print(arr16[1][3])

2
1
4
3
6
5
8
7


In [68]:
print(arr16[::,:1:1])

[[2]
 [1]]


In [69]:
print(arr16[::,:4])

[[2 4 6 8]
 [1 3 5 7]]


In [70]:
print(arr16[1::])
print(arr16[0::2])

[[1 3 5 7]]
[[2 4 6 8]]


### Array Manipulation
        ->Reshape NumPy array
        ->
Transpose array        ->
Flatten array

In [71]:
arr17 = np.arange(1,7)

In [72]:
arr17

array([1, 2, 3, 4, 5, 6])

In [73]:
arr18 = arr17.reshape(2,3)
arr18

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
arr17.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
arr19 = np.arange(1,19)
arr19

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [76]:
arr20 = arr19.reshape(3,6)   # converted 1D array to 2D array
arr20

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [77]:
arr19.reshape(2,3,3)   # converted 2D aray to 3D array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [78]:
arr3d = arr19.reshape(3,2,3)     
print(arr3d)                        # changed into 3d array of different format

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [79]:
arr21 = arr19.reshape(2,1,3,3)
print(arr21)                            # changed into 4D array
print(arr21.ndim)

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]]


 [[[10 11 12]
   [13 14 15]
   [16 17 18]]]]
4


In [80]:
print(arr20)
print(arr20.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
(3, 6)


In [81]:
arr20trans = np.transpose(arr20)               # changes rows into column and column into rows
print(arr20trans)
print(arr20trans.shape)

[[ 1  7 13]
 [ 2  8 14]
 [ 3  9 15]
 [ 4 10 16]
 [ 5 11 17]
 [ 6 12 18]]
(6, 3)


In [82]:
arr22 = np.array([[0,1],[2,3]])
print(arr22)
print(arr22.shape)

[[0 1]
 [2 3]]
(2, 2)


In [83]:
arr22resized = np.resize(arr22,(3,3))          #  resized the 2,2 array to 3,3 array
print(arr22resized)
print(arr22resized.shape)

[[0 1 2]
 [3 0 1]
 [2 3 0]]
(3, 3)


In [84]:
oned = arr22.flatten()        # converted into 1d array
print(oned) 

[0 1 2 3]


In [85]:
print(arr3d.flatten('C'))         # reads the elements row by row

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [86]:
print(arr3d.flatten('F'))               # reads the elements column by column

[ 1  7 13  4 10 16  2  8 14  5 11 17  3  9 15  6 12 18]


In [87]:
print(arr3d.flatten('A'))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [88]:
print(arr3d.flatten('K'))         # preservs the order according to memory

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


### Operatins and Functions

In [89]:
data = np.array([[3,8],[1,6]])
one = np.ones((2,2),dtype="int")

In [90]:
print(data)
print(one)

[[3 8]
 [1 6]]
[[1 1]
 [1 1]]


In [91]:
res = data + one

In [92]:
print(res)

[[4 9]
 [2 7]]


### Broadcasting

In [93]:
arr25 = np.array([[1,2,3,4],[5,6,7,8]])
onearr = np.ones(4,dtype="int")
print(arr25)
print(onearr)
print(arr25.shape)                              ### this is called broadcasting
print(onearr.shape)

[[1 2 3 4]
 [5 6 7 8]]
[1 1 1 1]
(2, 4)
(4,)


In [94]:
print(arr25 + onearr)

[[2 3 4 5]
 [6 7 8 9]]


In [95]:
arr26 = np.array([4,7,90,2])
print(arr25 + arr26)

[[ 5  9 93  6]
 [ 9 13 97 10]]


In [96]:
arr27 = np.array([[1,2,3]])

In [97]:
arr27.ndim

2

In [98]:
arr28 = np.array([[1],[2],[3]])

In [99]:
arr28.ndim

2

In [100]:
print(arr27)
print(arr28)
print(arr27 + arr28)

[[1 2 3]]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [101]:
arr29 = np.array([[2,4,6,8],[5,6,8,0]])
arr30 = np.array([[1,3,4,7],[5,7,6,9]])
print(arr29.shape)
print(arr30.shape)

(2, 4)
(2, 4)


In [102]:
print(arr29+arr30)

[[ 3  7 10 15]
 [10 13 14  9]]


In [103]:
a=np.array([[4,3],[2,3]])
b=np.array([[3,1],[4,4]])
np.multiply(a,b)

array([[12,  3],
       [ 8, 12]])

In [104]:
np.dot(a,b)

array([[24, 16],
       [18, 14]])

In [105]:
np.divide(a,b)

array([[1.33333333, 3.        ],
       [0.5       , 0.75      ]])

## Aggregation Operation

In [106]:
arr26

array([ 4,  7, 90,  2])

In [107]:
print(arr26.min())

2


In [108]:
print(arr26.max())

90


In [109]:
print(arr26.sum())

103


In [110]:
arrr = arr30.transpose()

In [111]:
print(arrr)
print()
print(arrr.min())
print(arrr.min(axis=0))
print(arrr.min(axis=1))

[[1 5]
 [3 7]
 [4 6]
 [7 9]]

1
[1 5]
[1 3 4 7]


In [112]:
print(arrr)
print()
print(arrr.max())
print(arrr.max(axis=0))
print(arrr.max(axis=1))
print(arrr.sum())
print(arrr.sum(axis=0))
print(arrr.sum(axis=1))

[[1 5]
 [3 7]
 [4 6]
 [7 9]]

9
[7 9]
[5 7 6 9]
42
[15 27]
[ 6 10 10 16]


In [113]:
arr26

array([ 4,  7, 90,  2])

In [114]:
mean = arr26.mean()

In [115]:
print(mean)

25.75


In [116]:
print(np.median(arr26))

5.5


In [117]:
print(np.std(arr26))

37.13741374947911


In [118]:
print(np.var(arr26))

1379.1875


In [119]:
print(np.percentile(arr26,100))

90.0


In [120]:
a = np.array([1,2,3,4,5])
np.save('outfile',a)

In [121]:
b = np.load('outfile.npy')

In [122]:
b

array([1, 2, 3, 4, 5])

In [123]:
arr26

array([ 4,  7, 90,  2])

In [124]:
len(arr26)

4

In [125]:
rev_arr = arr26[::-1]
rev_arr

array([ 2, 90,  7,  4])

In [126]:
b

array([1, 2, 3, 4, 5])

In [127]:
b=np.array([1,11,2,5,7,3,9])
prime_array=np.array([])
for i in range(0,len(b)):
    if b[i]<=1:
        continue
    for j in range(2,i):
        if i%j == 0:
            break
    else:
        prime_array = np.append(prime_array,b[i])
print(prime_array)

[11.  2.  5.  3.]


In [128]:
nums = input("Enter the numbers sepratred by space:")
num_list  = nums.split()
num_array = np.array(num_list,dtype=int)
print(num_array)

Enter the numbers sepratred by space: 2 5 6 9 7 4 33 6 4


[ 2  5  6  9  7  4 33  6  4]


In [134]:
arr32 = np.array([[2,2],[1,2],[3,4]])
print(arr32)

[[2 2]
 [1 2]
 [3 4]]


In [135]:
print(arr32[1:])

[[1 2]
 [3 4]]
